# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: '3'
tasks:
  genkey:
    requires:
      vars: [FILE]
    cmd: >
      wg genkey
      | ansible-vault encrypt_string
      --stdin-name wg_private_key --output -
      >> {{.FILE}}
  pubkey:
    requires:
      vars: [FILE]
    env:
      PUBKEY:
        sh: >
          yq .wg_private_key
          < {{.FILE}}
          | ansible-vault decrypt -
          | wg pubkey
    cmd: >
      yq e ".wg_public_key = strenv(PUBKEY)"
      -i {{.FILE}}

  genkey:all:
    sources:
      - ./host_vars/*.yml
    cmd:
      for: sources
      task: genkey
      vars:
        FILE: '{{.ITEM}}'

  pubkey:all:
    sources:
      - ./host_vars/*.yml
    cmd:
      for: sources
      task: pubkey
      vars:
        FILE: '{{.ITEM}}'

  gen-local-config:
    requires:
      vars: [HOST]
    cmd: >
      ansible-playbook
      -i ./hosts.yml
      --limit={{.HOST}}
      ./playbooks/gen-local-config.yml

  provision:localhost:
    requires:
      vars: [HOST]
    cmd: >
      ansible-playbook
      -i ./hosts.yml
      --connection local -K
      --limit={{.HOST}}
      ./playbooks/provision.yml

  provision:
    requires:
      vars: [HOST]
    cmd: >
      ansible-playbook
      -i ./hosts.yml
      --limit={{.HOST}}
      ./playbooks/provision.yml
